SELECT USER_ID,NICKNAME,SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS LIKE 'DONE'
GROUP BY U.USER_ID, NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_PRICE ASC