-- SELECT I.ANIMAL_ID,O.NAME
-- FROM ANIMAL_INS I
-- INNER JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE I.DATETIME > O.DATETIME
-- ORDER BY I.DATETIME ASC;


SELECT I.ANIMAL_ID,I.NAME
FROM ANIMAL_INS I
WHERE I.DATETIME > (
    SELECT O.DATETIME
    FROM ANIMAL_OUTS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
)
ORDER BY I.DATETIME